### ISSUE TITLE
Not working on Mac os

### ISSUE THREAD

**Issue by Jonatthu** [Mpdreamz/shellprogressbar#32] opened 2018-09-12 00:55 UTC
I am having this issue

Jonathans-MacBook-Pro:osx.10.11-x64 jonatthu$ ./Generatthor

Unhandled Exception: System.NotSupportedException: Task bar progress only works on Windows
   at ShellProgressBar.ProgressBarOptions.set_EnableTaskBarProgress(Boolean value)
   at Generatthor.Program.Bootstrap() in /Users/jonatthu/Documents/Jonatthu/Generatthor/Generatthor/Program.cs:line 43
   at Generatthor.Program.Main(String[] args) in /Users/jonatthu/Documents/Jonatthu/Generatthor/Generatthor/Program.cs:line 100
Abort trap: 6
Jonathans-MacBook

Version <PackageReference Include="ShellProgressBar" Version="4.2.0" />

**Comment by dlech** [comment] 2018-09-12 02:56
Make sure `EnableTaskBarProgress` is set to false (this should be the default value on Mac). Like the error message says, it only works on Windows.

**Comment by Jonatthu** [comment] 2018-09-12 03:42
@dlech Yep now is working, by the way...
What is `EnableTaskBarProgress`?

**Comment by dlech** [comment] 2018-09-12 03:48
It shows progress on the application's icon in the Windows taskbar.

**Comment by Jonatthu** [comment] 2018-09-12 03:52
![image](https://user-images.githubusercontent.com/3742176/45401215-7a226900-b604-11e8-8fc4-687f1ce990e9.png)
@dlech 

But the result is still weird when finished, when is ticking is good but when finish show that

**Comment by Jonatthu** [comment] 2018-09-12 16:47
If I use pbar.Dispose(); works a little better,

**Comment by Mpdreamz** [comment] 2020-02-22 20:04
Closing this due to age (my bad) and the fact I can not reproduce. Feel free to comment here if this is still an issue. ty @dlech for anwering 👍

**Closed by Mpdreamz** 2020-02-22 20:04 UTC
